[theme]
primaryColor = "#00ffb4"
backgroundColor = "#050510"
secondaryBackgroundColor = "#0a0a2e"
textColor = "#ffffff"
font = "monospace"

[client]
showErrorDetails = false

[server]
headless = true
port = 8501
